# Generated by Django 4.1.4 on 2022-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('habilities', models.TextField(default='SOMESTRING', verbose_name='habilities')),
                ('Company', models.TextField(default='SOMESTRING', verbose_name='company')),
                ('Salary', models.TextField(default='SOMESTRING', verbose_name='salary')),
                ('region', models.TextField(default='SOMESTRING', verbose_name='regions')),
                ('data', models.TextField(default='SOMESTRING', verbose_name='data')),
            ],
        ),
    ]
