# Generated by Django 4.1.4 on 2023-01-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession Info', 'verbose_name_plural': 'Profession'},
        ),
    ]
